### ISSUE TITLE
24 hour clock made

### ISSUE THREAD

**Issue by lxjv** [LITdevs/OMGEX#14]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/litdevs/omgex/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of OMGEX.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

i want 24h clock

### Describe the solution you'd like

24 hour clock

### Describe alternatives you've considered

twenty three hour clock (bad)

**Comment by Vukkyy** [comment]
thank you for your feedback. the 23 hour clock sounds like a good idea and i will work on it

**Comment by Vukkyy** [comment]
Hi, OMGEX 1.5 is now rolling out and contains this functionality!
Simply set the new `force24h` option to true, pray my code isn't broken, and enjoy!

**Comment by Vukkyy** [comment]
IT DID NOT
WOW

**Comment by Vukkyy** [comment]
ok it was a single typo that broke the whole thing. good job me. 1.5.1 is now rolling out and has a *functional* force24h option
![image](https://niko.is-ne.at/5L5Rch_Kf.png)

enjoy!

**Comment by lxjv** [comment]
epic thank you vuky
