### ISSUE TITLE
Not working, unknown reason

### ISSUE THREAD

**Issue by madcaker** [LITdevs/OMGEX#15]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/litdevs/omgex/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of OMGEX.
- [X] I am not using a **modified version** of OMGEX.
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Vivaldi 5.5.2805.38

### Describe the bug/issue

Pasted code into custom head of omg.lol profile. No enabled features showing in preview or live site.

### Expected behavior

Omegex features enabled and showing on profile

### Screenshots

![snip1](https://user-images.githubusercontent.com/80106285/197383239-89ce258d-b38d-4356-bdf3-07b7ac7ca2b1.PNG)
![snip2](https://user-images.githubusercontent.com/80106285/197383241-7506cb75-5fac-46a9-9999-f767e91caf35.PNG)
![snip3](https://user-images.githubusercontent.com/80106285/197383242-329daf8d-a2ab-4786-81d7-48d2af04ec46.PNG)

**Comment by Vukkyy** [comment]
Did you press the "Save and publish" button?

**Comment by Vukkyy** [comment]
![image](https://niko.is-ne.at/5L5KlHf9z.png)
Also, this should be `promoteOMGEX: false` not `promoteOMGEX "false"`. :)

**Comment by madcaker** [comment]
Yes, I published it. I just tried changing it to false now and it didn't work.

I forgot to attach this as well.

![Capture](https://user-images.githubusercontent.com/80106285/197383503-6a2503d8-63a7-411c-a9a4-8c07fc755797.PNG)

**Comment by Vukkyy** [comment]
You forgot the `:` after promoteOMGEX. Does it work then?

**Comment by madcaker** [comment]
No.

**Comment by Vukkyy** [comment]
I appear to have confused you a little bit, sorry. If you just replace the code you have with this:
```
<script src="https://cdn.jsdelivr.net/gh/litdevs/omgex@latest/OMGEX.js"></script>
<script>
    window.addEventListener('load', function() {
        OMGEX({birthday: "July 3rd", timezone: "America/Detroit", promoteOMGEX: false);
    });
</script>
```
Does it work then? (Sorry if I'm annoying you with this, lol)

**Comment by madcaker** [comment]
Honestly I'm not sure how I managed to mess that up lol. I blame my poor sleep schedule.

It still doesn't seem to work.

**Comment by Vukkyy** [comment]
HA! My fault now, I forgot the `}`.

So instead of...
```
promoteOMGEX: false);
```
do...
```
promoteOMGEX: false});
```

**Comment by madcaker** [comment]
haha, It works now, thanks. I really should go to sleep soon, sorry for bugging you.
