### ISSUE TITLE
Karma counter for users without any points shows up as undefined

### ISSUE THREAD

**Issue by GilOliveira** [LITdevs/OMGEX#16]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/litdevs/omgex/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of OMGEX.
- [X] I am not using a **modified version** of OMGEX.
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

N/A

### Browser and version

N/A

### Describe the bug/issue

When configuring OMGEX with a omg.lol user without any karma on IRC, the karma counter shows up as "undefined".

### Reproducing

1. Have no karma on IRC 🥲
2. Setup OMGEX for your karma-less IRC account
3. You now have undefined karma!

### Expected behavior

It should show a 0.

### Screenshots

<img width="225" alt="image" src="https://user-images.githubusercontent.com/1360438/201205980-1b7547ce-89b5-48b0-bdab-6869f2f544c0.png">

### Console logs

```
XHR GET https://irc.social.lol/api/karma.php?address=gil
[HTTP/1.1 404 Not Found 356ms]
```

### Additional context

Apparently the issue appears to come from the fact that IRC users without karma make the API return a 404.

**Comment by newbold** [comment]
It’s probably easier for me to fix this on my end than for vukky to address it on his end, so I just did that. If someone has never received karma before, it’ll now return `0`. Thanks for pointing this out!

**Comment by GilOliveira** [comment]
> It’s probably easier for me to fix this on my end than for vukky to address it on his end, so I just did that. If someone has never received karma before, it’ll now return `0`. Thanks for pointing this out!

Hehe was guessing...
