### ISSUE TITLE
OMGEX clock no longer centered

### ISSUE THREAD

**Issue by Zacatero** [LITdevs/OMGEX#22]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/litdevs/omgex/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of OMGEX.
- [X] I am not using a **modified version** of OMGEX.
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11 22H2

### Browser and version

Edge, most recent

### Describe the bug/issue

The OMGEX clock is no longer centered

### Reproducing

1) Load into your profile that contains the OMGEX clock
2) Observe the clock

### Expected behavior

It used to be centered below the Location and Job info

### Screenshots

https://i.zacate.ro/msedge_6AHmtIQYnS.png

**Comment by Vukkyy** [comment]
This should be fixed in 1.6.1, you may have to clear your cache.
